In [2]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import plotly.offline as pyo

### Introduction to Plotly

1. Until now we did visualisations using Matplotlib, Seaborn and pandas. 
All of them produces static image files.

2. Plotly is company based out in Canada famous for it's products like Plotly and dash

3. Plotly creates interactive visualizations in the form of HTML files

4. Drawback - Can't work with a live data source

5. dash is used to create live data based dashboards.

In [3]:
match = pd.read_csv(r"D:\Coding Language\Python\DataSet\MergingJoining\matches.csv")
delivery=pd.read_csv(r"D:\Coding Language\Python\DataSet\datasets-session-17\deliveries.csv")
ipl=delivery.merge(match,left_on='match_id',right_on='id')
ipl.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'season', 'city', 'date', 'team1',
       'team2', 'toss_winner', 'toss_decision', 'result', 'dl_applied',
       'winner', 'win_by_runs', 'win_by_wickets', 'player_of_match', 'venue',
       'umpire1', 'umpire2', 'umpire3'],
      dtype='object')

In [4]:
# Scatter Plots
# x and y both have continus data

# problem :- We are going to draw a scatter plot between Batsman Avg(X axis) and
# Batsman Strike rate(Y axis) of the top 50 batsman in IPL(ALL time)

top50=ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(50).index.to_list()
new_ipl=ipl[ipl['batsman'].isin(top50)]
runs=new_ipl.groupby('batsman')['batsman_runs'].sum()
balls=new_ipl.groupby('batsman')['ball'].count()
strike=((runs/balls)*100)
strike=strike.reset_index()
strike.rename(columns={0: 'strike_rate'},inplace=True)
strike
# df=ipl[~ipl['player_dismissed'].isna()]
out=ipl['player_dismissed'].value_counts().reset_index()
runs=runs.reset_index()
strike=strike.merge(out,left_on='batsman',right_on='player_dismissed')
strike['avg']=runs['batsman_runs']/strike['count']
strike.drop(columns=['player_dismissed','count'],inplace=True)

In [5]:
# Plot scatter Plot here
trace=go.Scatter(x=strike['avg'],y=strike['strike_rate'],mode='markers',text=strike['batsman'],marker={'color':'green','size':16})
data=[trace]
layout=go.Layout(title='Batsman Avg vs SR',xaxis={'title':'Batsman Average'},yaxis={'title':'Batsman strike Rate'})
fig = go.Figure(data=data,layout=layout)
pyo.plot(fig,filename='top50.html')

'top50.html'

In [6]:
#2. Line Chart :- It's an extension of Scatter plot.Usually used to show a 
# time series data.
# Year by year performance
single=ipl[ipl['batsman']=='V Kohli']
performance=single.groupby('season')['batsman_runs'].sum().reset_index()
performance

single1=ipl[ipl['batsman']=='MS Dhoni']
performance1=single1.groupby('season')['batsman_runs'].sum().reset_index()
performance1

   season  batsman_runs
0    2008           414
1    2009           332
2    2010           287
3    2011           392
4    2012           357
5    2013           461
6    2014           371
7    2015           372
8    2016           284
9    2017           290

In [7]:
# Plot Line Chart here

trace=go.Scatter(x=performance['season'],y=performance['batsman_runs'],
                 mode='lines+markers',
                 marker={'color':'#00a65a'},name='Virat Kohli')

trace1=go.Scatter(x=performance1['season'],y=performance1['batsman_runs'],
                 mode='lines+markers',
                 name='MS Dhoni')

data=[trace,trace1]

layout=go.Layout(title='Year by Year Performance',
                 xaxis={'title':'Season'},
                 yaxis={'title':'Total runs'})

fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [8]:
# Bar Plot :- Use to show relation between one categorical and 1 numerical data

# There are 3 types of Bar Graphs
# 1. Stacked Bar Graph
# 2. Stacked Bar Graph
# 3. Overlayed Bar graph
top10=ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10).reset_index()
trace=go.Bar(x=top10['batsman'],y=top10['batsman_runs'])
data=[trace]

layout=go.Layout(title='Top 10 IPL batsamn',
                 xaxis={'title':'Batsman'},
                 yaxis={'title':'Runs'})

fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [9]:
# iw=top10.groupby(['batsman','inning'])['batsman_runs'].sum().reset_index()
list=top10.set_index('batsman').index.to_list()
top10_df=ipl[ipl['batsman'].isin(list)]
iw = top10_df.groupby(['batsman','inning'])['batsman_runs'].sum().reset_index()
one=iw[iw['inning']==1]
two=iw[iw['inning']==2]
one.rename(columns={'batsman_runs':'1st Innings'},inplace=True)
two.rename(columns={'batsman_runs':'2nd Innings'},inplace=True)
final=one.merge(two,on='batsman')[['batsman','1st Innings','2nd Innings']]
trace1 = go.Bar(x=final['batsman'],y=final['1st Innings'],name ='1st innings',
            marker={'color':'#00a65a'})

trace2 = go.Bar(x=final['batsman'],y=final['2nd Innings'],name ='2nd innings',
            marker={'color':"#0074a6"})
data=[trace1,trace2]
layout=go.Layout(title='Inning wise scores',
                 xaxis={'title':'Batsman'},
                 yaxis={'title':'runs'},
                 ) # barmode=stack/overlayed and by default nested

fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

C:\Users\prana\AppData\Local\Temp\ipykernel_22772\3870069503.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  one.rename(columns={'batsman_runs':'1st Innings'},inplace=True)
C:\Users\prana\AppData\Local\Temp\ipykernel_22772\3870069503.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  two.rename(columns={'batsman_runs':'2nd Innings'},inplace=True)

'temp-plot.html'

In [10]:
# Bubble Plot :-
new_ipl=new_ipl[new_ipl['batsman_runs']==6]
six=new_ipl.groupby('batsman')['batsman_runs'].count().reset_index()
strike=strike.merge(six,on='batsman')
strike.rename(columns={'batsman_runs':'sixes'},inplace=True)
strike

             batsman  strike_rate        avg  sixes
0     AB de Villiers   145.129059  38.307692    158
1       AC Gilchrist   133.054662  27.223684     92
2           AJ Finch   126.299213  27.186441     59
3          AM Rahane   117.486549  33.593407     60
4          AT Rayudu   123.014257  27.146067     79
5        BB McCullum   126.318203  28.112245    124
6           BJ Hodge   121.422376  33.333333     43
7           CH Gayle   144.194313  41.022472    266
8          DA Miller   137.709251  34.733333     78
9          DA Warner   138.318401  40.140000    160
10          DJ Bravo   122.286822  22.945455     48
11         DJ Hussey   120.072661  26.979592     60
12  DPMD Jayawardene   118.791064  28.250000     40
13          DR Smith   132.279534  28.392857    117
14      F du Plessis   124.161074  30.116279     38
15         G Gambhir   120.361200  31.541985     58
16        GJ Maxwell   157.564103  25.081633     82
17         JH Kallis   105.936272  28.552941     44
18         JP Duminy   121.970624  39.860000     78
19        KA Pollard   140.621266  28.707317    148
20     KC Sangakkara   118.469101  25.953846     27
21        KD Karthik   123.008475  24.811966     71
22           KK Nair   124.650161  25.173913     26
23           M Vijay   120.028681  26.431579     89
24        MEK Hussey   119.963592  38.764706     52
25         MK Pandey   116.938453  28.500000     65
26         MK Tiwary   114.127424  29.428571     39
27          MS Dhoni   132.835821  37.872340    156
28           NV Ojha   114.528024  20.986486     79
29          PA Patel   112.718447  21.700935     35
30          R Dravid   113.347237  28.233766     28
31         RA Jadeja   118.792867  24.055556     57
32         RG Sharma   128.497251  32.612403    173
33        RV Uthappa   127.635135  29.515625    125
34       S Badrinath   115.742972  30.659574     28
35          S Dhawan   118.502496  32.669725     71
36        SC Ganguly   101.734540  25.452830     42
37          SE Marsh   130.109775  39.507937     78
38          SK Raina   134.995548  33.940299    174
39         SPD Smith   128.507127  37.239130     45
40      SR Tendulkar   114.187867  33.826087     29
41         SR Watson   134.838379  30.917647    122
42         SS Tiwary   114.851485  28.355556     45
43         SV Samson   122.403433  25.464286     57
44        TM Dilshan   110.124164  26.813953     24
45           V Kohli   126.588437  37.483051    160
46          V Sehwag   148.827059  27.555556    106
47           WP Saha   127.727646  25.524590     57
48         YK Pathan   140.751445  29.816327    149
49      Yuvraj Singh   126.390244  25.653465    141