## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [2]:
# code here
import pandas as pd
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
titanic_df 
titanic_df.groupby('Pclass')['Age'].agg(average_age='mean',missing_value=lambda x:x.isna().sum())

        average_age  missing_value
Pclass
1         38.233441             30
2         29.877630             11
3         25.140620            136

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [3]:
# code here
df=titanic_df.groupby('Pclass')
df['Embarked'].transform(lambda x:x.fillna(x.mode().iloc[0]))

# transform :- transform() applies a function to each group and returns the same number of rows as the original data.

print(
    titanic_df.groupby("Pclass")["Embarked"]
              .value_counts(ascending=True)
)

Pclass  Embarked
1       Q             2
        C            85
        S           127
2       Q             3
        C            17
        S           164
3       C            66
        Q            72
        S           353
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [4]:
# code here
titanic_df

group_fare=titanic_df.groupby(['Embarked','Pclass'])['Fare'].agg(lambda x:x.mean())
round(group_fare).unstack().to_dict(orient='index')

{'C': {1: 105.0, 2: 25.0, 3: 11.0},
 'Q': {1: 90.0, 2: 12.0, 3: 11.0},
 'S': {1: 70.0, 2: 20.0, 3: 15.0}}

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [5]:
# code here

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
team_group=fifa_df.groupby('Team')
def z_normalizarion(group,column):
    return group[column].apply(lambda x: (x-x.mean())/x.std())
cols = [
    "Passes",
    "Passes Completed",
    "Attempted Line Breaks",
    "Completed Line Breaks"
]
z_normalizarion(team_group,cols)
maximum_pass=team_group['Passes'].max()
minimum_pass=team_group['Passes'].min()
minimum_yellowCard=team_group['Yellow Cards'].min()
maximum_yellowCard=team_group['Yellow Cards'].max()
avg_yellowCard=team_group['Yellow Cards'].mean()
maximum_attemptLineBreaks=team_group['Attempted Line Breaks'].max()
minimum_attemptLineBreaks=team_group['Attempted Line Breaks'].min()
std_attemptLineBreaks=team_group['Attempted Line Breaks'].std()
avg_possesion=team_group['Possession (%)'].mean()
maximum_pass

Team
Argentina          862
Australia          466
Belgium            685
Brazil             695
Cameroon           500
Canada             536
Costa Rica         454
Croatia            724
Denmark            650
Ecuador            484
England            810
France             734
Germany            827
Ghana              460
Iran               463
Japan              591
Korea Republic     548
Mexico             500
Morocco            583
Netherlands        786
Poland             466
Portugal           678
Qatar              457
Saudi Arabia       560
Senegal            511
Serbia             513
Spain             1070
Switzerland        512
Tunisia            501
United States      572
Uruguay            528
Wales              508
Name: Passes, dtype: int64

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [6]:
# code here
batsman_runs=pd.read_csv(r"C:\Users\prana\Downloads\ipl_deliveries.csv")
inning_bat = batsman_runs[batsman_runs['innings']==2]
inning_bat.groupby(['ID','batter'])['batsman_run'].sum().sort_values(ascending=False).head(1)
# inning_bat.groupby('batter')['ballnumber'].sum().sort_values(ascending=False)
# if(inning_bat.groupby('batter')['ballnumber'].sum()>100):
#     pass
batsman_runs.head(234)
temp_df=inning_bat[~(inning_bat['extra_type']=='wides')]
temp_df=temp_df.groupby('batter').agg(
    {
        'batsman_run':"sum",
        'ballnumber':"count"
    }
)
temp_df['strike_rate']=temp_df['batsman_run'] / temp_df['ballnumber'] *100
temp_df[temp_df['ballnumber']>100]
batsman_runs

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225950,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225951,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225952,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225953,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [7]:
# code here
batsman_runs["isbatterOut"]=batsman_runs['batter']==batsman_runs['player_out']
batsman_runs.groupby(['bowler','batter']).agg(
    {
        "isbatterOut":"sum",
        "batsman_run":"sum"
    }
).sort_values(by=['isbatterOut',"batsman_run"],ascending=[False,True]).head()

                           isbatterOut  batsman_run
bowler         batter
Z Khan         MS Dhoni              7           74
Sandeep Sharma V Kohli               7           78
A Mishra       RG Sharma             7           87
R Ashwin       RV Uthappa            7          123
SP Narine      RG Sharma             7          137

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [8]:
# code here
df=batsman_runs[['player1','player2']]=batsman_runs[['batter','non-striker']].apply(lambda x: pd.Series(sorted(x)),axis=1)
batsman_runs.groupby(['player1','player2'])['total_run'].sum().sort_values(ascending=False)

player1         player2
AB de Villiers  V Kohli        3134
CH Gayle        V Kohli        2802
DA Warner       S Dhawan       2357
G Gambhir       RV Uthappa     1906
KL Rahul        MA Agarwal     1731
                               ...
A Choudhary     S Badree          0
T Stubbs        Tilak Varma       0
A Mishra        CL White          0
M Muralitharan  MS Gony           0
M Morkel        S Nadeem          0
Name: total_run, Length: 4259, dtype: int64

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [ ]:
# code here
df8=batsman_runs.groupby(['player1','player2']).agg({
    "total_run":"sum",
    "ballnumber":"count",
    "isWicketDelivery":"sum"
}).reset_index()
te

NameError: name 'te' is not defined

: